server:
  port: 8123
  error:
    path: /error1
cors:
  headers: AccessToken,AuthInfo
logging:
  path: /Users/luzhihao/tmp/logs
  level:
    cn.enigma: debug
  config: classpath:logback-spring.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"